apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lroc
spec:
  resources:
    requests:
      storage: 1Ti  # This is the least amount of storage available for the data
                      # It must be less or equal to the amount of storage in the pv to be claimed.
  accessModes:
    - ReadWriteMany # This must be defined to be claimed by the pv created.
  storageClassName: sc-lroc
